@API = http://localhost:3000

GET {{API}}

###
POST {{API}}/usuarios/registro
Content-Type: application/json

{
  "nombre": "Prueba",
  "apellidos": "Pruebas Pruebas",
  "telefono": "123456789",
  "correo": "prueba@gmail.com",
  "password": "contraseña"
}

###
POST {{API}}/usuarios/login
Content-Type: application/json

{
  "correo": "prueba@gmail.com",
  "password": "contraseña"
}

###
GET {{API}}/usuarios/1
Authorization: Bearer 480fc4fb9f04d841b04bd1d0cc4a5021c9d08015

###
PUT {{API}}/usuarios
Authorization:Bearer 2b502864d041bc7ce743fa4d7090b4c0d63f50ba
Content-Type: application/json

{
  "nombre": "Pruebas",
  "apellidos": "Pruebas Pruebas",
  "telefono": 123456789,
  "correo": "prueba@gmail.com"
}


###
DELETE {{API}}/usuarios
Authorization:Bearer 2b502864d041bc7ce743fa4d7090b4c0d63f50ba
Content-Type: application/json

{
  "nombre": "Pruebas",
  "apellidos": "Pruebas Pruebas",
  "telefono": 123456789,
  "correo": "prueba@gmail.com"
}


